export const FETCH_PATIENTS = "FETCH_PATIENTS";
export const SET_PATIENTS = "SET_PATIENTS";
export const FETCH_APPOINTMENTS = "FETCH_APPOINTMENTS";
export const SET_APPOINTMENTS = "SET_APPOINTMENTS";
export const FETCH_MEDICAL_RECORDS = "FETCH_MEDICAL_RECORDS";
export const SET_MEDICAL_RECORDS = "SET_MEDICAL_RECORDS";
